quiet: False
with-expecter: True
filename: "{{ .InterfaceName | snakecase }}.go"
outpkg: "mocks"
dir: "{{.InterfaceDir}}/mocks"

packages:
  github.com/dan13ram/wpokt-oracle/db:
    interfaces:
      Database:
      DB:
  github.com/dan13ram/wpokt-oracle/cosmos/client:
    interfaces:
      CosmosClient:
  github.com/dan13ram/wpokt-oracle/ethereum/client:
    interfaces:
      EthereumClient:
      MailboxContract:
      MailboxDispatchIterator:
      MintControllerContract:
      MintControllerFulfillmentIterator:
      WarpISMContract:
  github.com/cosmos/cosmos-sdk/client:
    config: 
      dir: "cosmos/client/mocks"
    interfaces:
      TxBuilder:
      TxConfig:
  github.com/cosmos/cosmos-sdk/x/auth/signing:
    config:
      dir: "cosmos/client/mocks"
    interfaces:
      Tx:
