mnemonic: "example_mnemonic"
health_check:
  interval_ms: 5000
  read_last_health: true
logger:
  level: "info"
mongodb:
  uri: "mongodb://localhost:27017"
  database: "example_db"
  timeout_ms: 10000
ethereum_networks:
  - start_block_number: 1000000
    confirmations: 0
    rpc_url: "http://localhost:8545"
    rpc_timeout_ms: 5000
    chain_id: 1
    mailbox_address: "0x123456789abcdef"
    mint_controller_address: "0xabcdef123456789"
    oracle_addresses:
      - "0xoracleAddress1"
      - "0xoracleAddress2"
    message_monitor:
      enabled: true
      interval_ms: 60000
    message_signer:
      enabled: true
      interval_ms: 60000
    message_processor:
      enabled: true
      interval_ms: 60000
cosmos_networks:
  - start_block_height: 500000
    confirmations: 0
    rpc_url: "http://localhost:26657"
    rpc_timeout_ms: 5000
    chain_id: "cosmoshub-4"
    tx_fee: 0
    bech32_prefix: "cosmos"
    multisig_address: "cosmos1abcdefg"
    multisig_public_keys:
      - "pubKey1"
      - "pubKey2"
    multisig_threshold: 2
    message_monitor:
      enabled: true
      interval_ms: 60000
    message_signer:
      enabled: true
      interval_ms: 60000
    message_processor:
      enabled: true
      interval_ms: 60000
