services:
  validator:
    image: dan13ram/wpokt-oracle
    build:
      context: .
      target: base
    environment:
      # mongodb
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_TIMEOUT_SECS: ${MONGODB_TIMEOUT_SECS}

      # ethereum
      ETH_PRIVATE_KEY: ${ETH_PRIVATE_KEY}
      ETH_RPC_URL: ${ETH_RPC_URL}
      ETH_CHAIN_ID: ${ETH_CHAIN_ID}
      ETH_START_BLOCK_NUMBER: ${ETH_START_BLOCK_NUMBER}
      ETH_CONFIRMATIONS: ${ETH_CONFIRMATIONS}
      ETH_RPC_TIMEOUT_SECS: ${ETH_RPC_TIMEOUT_SECS}
      ETH_WRAPPED_POCKET_ADDRESS: ${ETH_WRAPPED_POCKET_ADDRESS}
      ETH_MINT_CONTROLLER_ADDRESS: ${ETH_MINT_CONTROLLER_ADDRESS}
      ETH_VALIDATOR_ADDRESSES: ${ETH_VALIDATOR_ADDRESSES}

      # pocket
      POKT_PRIVATE_KEY: ${POKT_PRIVATE_KEY}
      POKT_RPC_URL: ${POKT_RPC_URL}
      POKT_CHAIN_ID: ${POKT_CHAIN_ID}
      POKT_START_HEIGHT: ${POKT_START_HEIGHT}
      POKT_CONFIRMATIONS: ${POKT_CONFIRMATIONS}
      POKT_RPC_TIMEOUT_SECS: ${POKT_RPC_TIMEOUT_SECS}
      POKT_TX_FEE: ${POKT_TX_FEE}
      POKT_VAULT_ADDRESS: ${POKT_VAULT_ADDRESS}
      POKT_MULTISIG_PUBLIC_KEYS: ${POKT_MULTISIG_PUBLIC_KEYS}

      # google secret manager
      GOOGLE_SECRET_MANAGER_ENABLED: ${GOOGLE_SECRET_MANAGER_ENABLED}
      GOOGLE_MONGO_SECRET_NAME: ${GOOGLE_MONGO_SECRET_NAME}
      GOOGLE_POKT_SECRET_NAME: ${GOOGLE_POKT_SECRET_NAME}
      GOOGLE_ETH_SECRET_NAME: ${GOOGLE_ETH_SECRET_NAME}

      # mint monitor
      MINT_MONITOR_ENABLED: ${MINT_MONITOR_ENABLED}
      MINT_MONITOR_INTERVAL_SECS: ${MINT_MONITOR_INTERVAL_SECS}

      # mint signer
      MINT_SIGNER_ENABLED: ${MINT_SIGNER_ENABLED}
      MINT_SIGNER_INTERVAL_SECS: ${MINT_SIGNER_INTERVAL_SECS}

      # mint executor
      MINT_EXECUTOR_ENABLED: ${MINT_EXECUTOR_ENABLED}
      MINT_EXECUTOR_INTERVAL_SECS: ${MINT_EXECUTOR_INTERVAL_SECS}

      # burn monitor
      BURN_MONITOR_ENABLED: ${BURN_MONITOR_ENABLED}
      BURN_MONITOR_INTERVAL_SECS: ${BURN_MONITOR_INTERVAL_SECS}

      # burn signer
      BURN_SIGNER_ENABLED: ${BURN_SIGNER_ENABLED}
      BURN_SIGNER_INTERVAL_SECS: ${BURN_SIGNER_INTERVAL_SECS}

      # burn executor
      BURN_EXECUTOR_ENABLED: ${BURN_EXECUTOR_ENABLED}
      BURN_EXECUTOR_INTERVAL_SECS: ${BURN_EXECUTOR_INTERVAL_SECS}

      # health check
      HEALTH_CHECK_INTERVAL_SECS: ${HEALTH_CHECK_INTERVAL_SECS}

      # logging
      LOGGER_LEVEL: ${LOGGER_LEVEL}
