// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	autogen "github.com/dan13ram/wpokt-oracle/ethereum/autogen"

	mock "github.com/stretchr/testify/mock"
)

// MockMailboxDispatchIterator is an autogenerated mock type for the MailboxDispatchIterator type
type MockMailboxDispatchIterator struct {
	mock.Mock
}

type MockMailboxDispatchIterator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailboxDispatchIterator) EXPECT() *MockMailboxDispatchIterator_Expecter {
	return &MockMailboxDispatchIterator_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *MockMailboxDispatchIterator) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMailboxDispatchIterator_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMailboxDispatchIterator_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockMailboxDispatchIterator_Expecter) Close() *MockMailboxDispatchIterator_Close_Call {
	return &MockMailboxDispatchIterator_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockMailboxDispatchIterator_Close_Call) Run(run func()) *MockMailboxDispatchIterator_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMailboxDispatchIterator_Close_Call) Return(_a0 error) *MockMailboxDispatchIterator_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailboxDispatchIterator_Close_Call) RunAndReturn(run func() error) *MockMailboxDispatchIterator_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with given fields:
func (_m *MockMailboxDispatchIterator) Error() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMailboxDispatchIterator_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockMailboxDispatchIterator_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *MockMailboxDispatchIterator_Expecter) Error() *MockMailboxDispatchIterator_Error_Call {
	return &MockMailboxDispatchIterator_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *MockMailboxDispatchIterator_Error_Call) Run(run func()) *MockMailboxDispatchIterator_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMailboxDispatchIterator_Error_Call) Return(_a0 error) *MockMailboxDispatchIterator_Error_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailboxDispatchIterator_Error_Call) RunAndReturn(run func() error) *MockMailboxDispatchIterator_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Event provides a mock function with given fields:
func (_m *MockMailboxDispatchIterator) Event() *autogen.MailboxDispatch {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Event")
	}

	var r0 *autogen.MailboxDispatch
	if rf, ok := ret.Get(0).(func() *autogen.MailboxDispatch); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*autogen.MailboxDispatch)
		}
	}

	return r0
}

// MockMailboxDispatchIterator_Event_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Event'
type MockMailboxDispatchIterator_Event_Call struct {
	*mock.Call
}

// Event is a helper method to define mock.On call
func (_e *MockMailboxDispatchIterator_Expecter) Event() *MockMailboxDispatchIterator_Event_Call {
	return &MockMailboxDispatchIterator_Event_Call{Call: _e.mock.On("Event")}
}

func (_c *MockMailboxDispatchIterator_Event_Call) Run(run func()) *MockMailboxDispatchIterator_Event_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMailboxDispatchIterator_Event_Call) Return(_a0 *autogen.MailboxDispatch) *MockMailboxDispatchIterator_Event_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailboxDispatchIterator_Event_Call) RunAndReturn(run func() *autogen.MailboxDispatch) *MockMailboxDispatchIterator_Event_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function with given fields:
func (_m *MockMailboxDispatchIterator) Next() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockMailboxDispatchIterator_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockMailboxDispatchIterator_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockMailboxDispatchIterator_Expecter) Next() *MockMailboxDispatchIterator_Next_Call {
	return &MockMailboxDispatchIterator_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockMailboxDispatchIterator_Next_Call) Run(run func()) *MockMailboxDispatchIterator_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMailboxDispatchIterator_Next_Call) Return(_a0 bool) *MockMailboxDispatchIterator_Next_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailboxDispatchIterator_Next_Call) RunAndReturn(run func() bool) *MockMailboxDispatchIterator_Next_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMailboxDispatchIterator creates a new instance of MockMailboxDispatchIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailboxDispatchIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailboxDispatchIterator {
	mock := &MockMailboxDispatchIterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
