// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	big "math/big"

	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"

	mock "github.com/stretchr/testify/mock"

	util "github.com/dan13ram/wpokt-oracle/ethereum/util"
)

// MockWarpISMContract is an autogenerated mock type for the WarpISMContract type
type MockWarpISMContract struct {
	mock.Mock
}

type MockWarpISMContract_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWarpISMContract) EXPECT() *MockWarpISMContract_Expecter {
	return &MockWarpISMContract_Expecter{mock: &_m.Mock}
}

// Eip712Domain provides a mock function with given fields: opts
func (_m *MockWarpISMContract) Eip712Domain(opts *bind.CallOpts) (util.DomainData, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Eip712Domain")
	}

	var r0 util.DomainData
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) (util.DomainData, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) util.DomainData); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Get(0).(util.DomainData)
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWarpISMContract_Eip712Domain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Eip712Domain'
type MockWarpISMContract_Eip712Domain_Call struct {
	*mock.Call
}

// Eip712Domain is a helper method to define mock.On call
//   - opts *bind.CallOpts
func (_e *MockWarpISMContract_Expecter) Eip712Domain(opts interface{}) *MockWarpISMContract_Eip712Domain_Call {
	return &MockWarpISMContract_Eip712Domain_Call{Call: _e.mock.On("Eip712Domain", opts)}
}

func (_c *MockWarpISMContract_Eip712Domain_Call) Run(run func(opts *bind.CallOpts)) *MockWarpISMContract_Eip712Domain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bind.CallOpts))
	})
	return _c
}

func (_c *MockWarpISMContract_Eip712Domain_Call) Return(_a0 util.DomainData, _a1 error) *MockWarpISMContract_Eip712Domain_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWarpISMContract_Eip712Domain_Call) RunAndReturn(run func(*bind.CallOpts) (util.DomainData, error)) *MockWarpISMContract_Eip712Domain_Call {
	_c.Call.Return(run)
	return _c
}

// SignerThreshold provides a mock function with given fields: opts
func (_m *MockWarpISMContract) SignerThreshold(opts *bind.CallOpts) (*big.Int, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for SignerThreshold")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) (*big.Int, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) *big.Int); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWarpISMContract_SignerThreshold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignerThreshold'
type MockWarpISMContract_SignerThreshold_Call struct {
	*mock.Call
}

// SignerThreshold is a helper method to define mock.On call
//   - opts *bind.CallOpts
func (_e *MockWarpISMContract_Expecter) SignerThreshold(opts interface{}) *MockWarpISMContract_SignerThreshold_Call {
	return &MockWarpISMContract_SignerThreshold_Call{Call: _e.mock.On("SignerThreshold", opts)}
}

func (_c *MockWarpISMContract_SignerThreshold_Call) Run(run func(opts *bind.CallOpts)) *MockWarpISMContract_SignerThreshold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bind.CallOpts))
	})
	return _c
}

func (_c *MockWarpISMContract_SignerThreshold_Call) Return(_a0 *big.Int, _a1 error) *MockWarpISMContract_SignerThreshold_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWarpISMContract_SignerThreshold_Call) RunAndReturn(run func(*bind.CallOpts) (*big.Int, error)) *MockWarpISMContract_SignerThreshold_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatorCount provides a mock function with given fields: opts
func (_m *MockWarpISMContract) ValidatorCount(opts *bind.CallOpts) (*big.Int, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for ValidatorCount")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) (*big.Int, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) *big.Int); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWarpISMContract_ValidatorCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatorCount'
type MockWarpISMContract_ValidatorCount_Call struct {
	*mock.Call
}

// ValidatorCount is a helper method to define mock.On call
//   - opts *bind.CallOpts
func (_e *MockWarpISMContract_Expecter) ValidatorCount(opts interface{}) *MockWarpISMContract_ValidatorCount_Call {
	return &MockWarpISMContract_ValidatorCount_Call{Call: _e.mock.On("ValidatorCount", opts)}
}

func (_c *MockWarpISMContract_ValidatorCount_Call) Run(run func(opts *bind.CallOpts)) *MockWarpISMContract_ValidatorCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bind.CallOpts))
	})
	return _c
}

func (_c *MockWarpISMContract_ValidatorCount_Call) Return(_a0 *big.Int, _a1 error) *MockWarpISMContract_ValidatorCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWarpISMContract_ValidatorCount_Call) RunAndReturn(run func(*bind.CallOpts) (*big.Int, error)) *MockWarpISMContract_ValidatorCount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWarpISMContract creates a new instance of MockWarpISMContract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWarpISMContract(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWarpISMContract {
	mock := &MockWarpISMContract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
