mnemonic: "wink giant track dwarf visa feed visual drip play grant royal noise"
health_check:
  interval_ms: 10000
  read_last_health: false
logger:
  level: "debug"
  format: "json"
mongodb:
  uri: "mongodb://localhost:27017/test?retryWrites=true&w=majority"
  database: "test"
  timeout_ms: 10000
ethereum_networks:
  - start_block_height: 1
    confirmations: 0
    rpc_url: "http://127.0.0.1:38545"
    timeout_ms: 5000
    chain_id: 38545
    chain_name: "anvil-one"
    mailbox_address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
    warp_ism_address: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
    omni_token_address: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
    mint_controller_address: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707"
    oracle_addresses:
      - "0x0E90A32Df6f6143F1A91c25d9552dCbc789C34Eb"
      - "0x958d1F55E14Cba24a077b9634F16f83565fc9411"
      - "0x4c672Edd2ec8eac8f0F1709f33de9A2E786e6912"
    message_monitor:
      enabled: true
      interval_ms: 10000
    message_signer:
      enabled: true
      interval_ms: 10000
    message_relayer:
      enabled: true
      interval_ms: 10000
  - start_block_height: 1
    confirmations: 0
    rpc_url: "http://127.0.0.1:38546"
    timeout_ms: 5000
    chain_id: 38546
    chain_name: "anvil-two"
    mailbox_address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
    warp_ism_address: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
    omni_token_address: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
    mint_controller_address: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707"
    oracle_addresses:
      - "0x0E90A32Df6f6143F1A91c25d9552dCbc789C34Eb"
      - "0x958d1F55E14Cba24a077b9634F16f83565fc9411"
      - "0x4c672Edd2ec8eac8f0F1709f33de9A2E786e6912"
    message_monitor:
      enabled: true
      interval_ms: 10000
    message_signer:
      enabled: true
      interval_ms: 10000
    message_relayer:
      enabled: true
      interval_ms: 10000
cosmos_network:
  start_block_height: 1
  confirmations: 0
  rpc_url: "http://localhost:36657"
  grpc_enabled: true
  grpc_host: 'localhost'
  grpc_port: 36658
  timeout_ms: 5000
  chain_id: "poktroll"
  chain_name: "pokt_localnet"
  tx_fee: 0
  bech32_prefix: "pokt"
  coin_denom: "upokt"
  multisig_address: "pokt13tsl3aglfyzf02n7x28x2ajzw94muu6y57k2ar"
  multisig_public_keys:
    - "026892de2ec7fdf3125bc1bfd2ff2590d2c9ba756f98a05e9e843ac4d2a1acd4d9"
    - "02faaaf0f385bb17381f36dcd86ab2486e8ff8d93440436496665ac007953076c2"
    - "02cae233806460db75a941a269490ca5165a620b43241edb8bc72e169f4143a6df"
  multisig_threshold: 2
  message_monitor:
    enabled: true
    interval_ms: 10000
  message_signer:
    enabled: true
    interval_ms: 10000
  message_relayer:
    enabled: true
    interval_ms: 10000
