#!/bin/sh

# Number of Ethereum networks
NUM_ETHEREUM_NETWORKS=${NUM_ETHEREUM_NETWORKS:-2}

# Loop over Ethereum networks
for i in $(seq 0 $(($NUM_ETHEREUM_NETWORKS - 1)))
do
  eval "export ETHEREUM_NETWORKS_${i}_START_BLOCK_HEIGHT=\${ETHEREUM_NETWORKS_${i}_START_BLOCK_HEIGHT}"
  eval "export ETHEREUM_NETWORKS_${i}_CONFIRMATIONS=\${ETHEREUM_NETWORKS_${i}_CONFIRMATIONS}"
  eval "export ETHEREUM_NETWORKS_${i}_RPC_URL=\${ETHEREUM_NETWORKS_${i}_RPC_URL}"
  eval "export ETHEREUM_NETWORKS_${i}_TIMEOUT_MS=\${ETHEREUM_NETWORKS_${i}_TIMEOUT_MS}"
  eval "export ETHEREUM_NETWORKS_${i}_CHAIN_ID=\${ETHEREUM_NETWORKS_${i}_CHAIN_ID}"
  eval "export ETHEREUM_NETWORKS_${i}_CHAIN_NAME=\${ETHEREUM_NETWORKS_${i}_CHAIN_NAME}"
  eval "export ETHEREUM_NETWORKS_${i}_MAILBOX_ADDRESS=\${ETHEREUM_NETWORKS_${i}_MAILBOX_ADDRESS}"
  eval "export ETHEREUM_NETWORKS_${i}_MINT_CONTROLLER_ADDRESS=\${ETHEREUM_NETWORKS_${i}_MINT_CONTROLLER_ADDRESS}"
  eval "export ETHEREUM_NETWORKS_${i}_OMNI_TOKEN_ADDRESS=\${ETHEREUM_NETWORKS_${i}_OMNI_TOKEN_ADDRESS}"
  eval "export ETHEREUM_NETWORKS_${i}_WARP_ISM_ADDRESS=\${ETHEREUM_NETWORKS_${i}_WARP_ISM_ADDRESS}"
  eval "export ETHEREUM_NETWORKS_${i}_ORACLE_ADDRESSES=\${ETHEREUM_NETWORKS_${i}_ORACLE_ADDRESSES}"
  eval "export ETHEREUM_NETWORKS_${i}_MESSAGE_MONITOR_ENABLED=\${ETHEREUM_NETWORKS_${i}_MESSAGE_MONITOR_ENABLED}"
  eval "export ETHEREUM_NETWORKS_${i}_MESSAGE_MONITOR_INTERVAL_MS=\${ETHEREUM_NETWORKS_${i}_MESSAGE_MONITOR_INTERVAL_MS}"
  eval "export ETHEREUM_NETWORKS_${i}_MESSAGE_SIGNER_ENABLED=\${ETHEREUM_NETWORKS_${i}_MESSAGE_SIGNER_ENABLED}"
  eval "export ETHEREUM_NETWORKS_${i}_MESSAGE_SIGNER_INTERVAL_MS=\${ETHEREUM_NETWORKS_${i}_MESSAGE_SIGNER_INTERVAL_MS}"
  eval "export ETHEREUM_NETWORKS_${i}_MESSAGE_RELAYER_ENABLED=\${ETHEREUM_NETWORKS_${i}_MESSAGE_RELAYER_ENABLED}"
  eval "export ETHEREUM_NETWORKS_${i}_MESSAGE_RELAYER_INTERVAL_MS=\${ETHEREUM_NETWORKS_${i}_MESSAGE_RELAYER_INTERVAL_MS}"
done
