#!/bin/sh

# Number of Ethereum networks
NUM_ETHEREUM_NETWORKS=${NUM_ETHEREUM_NETWORKS}  # Default to 1 if not set

if [ -z "$NUM_ETHEREUM_NETWORKS" ]; then
  echo "NUM_ETHEREUM_NETWORKS is not set."
  exit 1
fi

# Loop over Ethereum networks
for i in $(seq 0 $(($NUM_ETHEREUM_NETWORKS - 1)))
do
  export ETHEREUM_NETWORKS_${i}_START_BLOCK_HEIGHT=${!ETHEREUM_NETWORKS_${i}_START_BLOCK_HEIGHT:-1000000}
  export ETHEREUM_NETWORKS_${i}_CONFIRMATIONS=${!ETHEREUM_NETWORKS_${i}_CONFIRMATIONS:-12}
  export ETHEREUM_NETWORKS_${i}_RPC_URL=${!ETHEREUM_NETWORKS_${i}_RPC_URL:-https://mainnet.infura.io/v3/your-infura-project-id}
  export ETHEREUM_NETWORKS_${i}_TIMEOUT_MS=${!ETHEREUM_NETWORKS_${i}_TIMEOUT_MS:-30000}
  export ETHEREUM_NETWORKS_${i}_CHAIN_ID=${!ETHEREUM_NETWORKS_${i}_CHAIN_ID:-1}
  export ETHEREUM_NETWORKS_${i}_CHAIN_NAME=${!ETHEREUM_NETWORKS_${i}_CHAIN_NAME:-mainnet}
  export ETHEREUM_NETWORKS_${i}_MAILBOX_ADDRESS=${!ETHEREUM_NETWORKS_${i}_MAILBOX_ADDRESS:-0xYourMailboxAddress}
  export ETHEREUM_NETWORKS_${i}_MINT_CONTROLLER_ADDRESS=${!ETHEREUM_NETWORKS_${i}_MINT_CONTROLLER_ADDRESS:-0xYourMintControllerAddress}
  export ETHEREUM_NETWORKS_${i}_OMNI_TOKEN_ADDRESS=${!ETHEREUM_NETWORKS_${i}_OMNI_TOKEN_ADDRESS:-0xYourOmniTokenAddress}
  export ETHEREUM_NETWORKS_${i}_WARP_ISM_ADDRESS=${!ETHEREUM_NETWORKS_${i}_WARP_ISM_ADDRESS:-0xYourWarpISMAddress}
  export ETHEREUM_NETWORKS_${i}_ORACLE_ADDRESSES=${!ETHEREUM_NETWORKS_${i}_ORACLE_ADDRESSES:-0xOracle1Address,0xOracle2Address}
  export ETHEREUM_NETWORKS_${i}_MESSAGE_MONITOR_ENABLED=${!ETHEREUM_NETWORKS_${i}_MESSAGE_MONITOR_ENABLED:-true}
  export ETHEREUM_NETWORKS_${i}_MESSAGE_MONITOR_INTERVAL_MS=${!ETHEREUM_NETWORKS_${i}_MESSAGE_MONITOR_INTERVAL_MS:-5000}
  export ETHEREUM_NETWORKS_${i}_MESSAGE_SIGNER_ENABLED=${!ETHEREUM_NETWORKS_${i}_MESSAGE_SIGNER_ENABLED:-true}
  export ETHEREUM_NETWORKS_${i}_MESSAGE_SIGNER_INTERVAL_MS=${!ETHEREUM_NETWORKS_${i}_MESSAGE_SIGNER_INTERVAL_MS:-5000}
  export ETHEREUM_NETWORKS_${i}_MESSAGE_RELAYER_ENABLED=${!ETHEREUM_NETWORKS_${i}_MESSAGE_RELAYER_ENABLED:-true}
  export ETHEREUM_NETWORKS_${i}_MESSAGE_RELAYER_INTERVAL_MS=${!ETHEREUM_NETWORKS_${i}_MESSAGE_RELAYER_INTERVAL_MS:-5000}
done
