version: "3.8"

services:
  wpokt-hyperlane-one:
    image: dan13ram/wpokt-hyperlane-contracts:v0.0.1
    network_mode: host
    environment:
      PORT: "38545"
      CHAIN_ID: "38545"
    ports:
      - "38545:38545"
    expose:
      - "38545"

  wpokt-hyperlane-two:
    image: dan13ram/wpokt-hyperlane-contracts:v0.0.1
    network_mode: host
    environment:
      PORT: "38546"
      CHAIN_ID: "38546"
    ports:
      - "38546:38546"
    expose:
      - "38546"

  oracle-one:
    image: dan13ram/wpokt-oracle:v0.0.1
    network_mode: host
    entrypoint: ["/bin/sh", "-c", "sleep 30 && /app/set_eth_envs.sh && /bin/oracle --yaml /app/defaults/config.local.one.yml"]

  oracle-two:
    image: dan13ram/wpokt-oracle:v0.0.1
    network_mode: host
    entrypoint: ["/bin/sh", "-c", "sleep 30 && /app/set_eth_envs.sh && /bin/oracle --yaml /app/defaults/config.local.two.yml"]

  oracle-three:
    image: dan13ram/wpokt-oracle:v0.0.1
    network_mode: host
    entrypoint: ["/bin/sh", "-c", "sleep 30 && /app/set_eth_envs.sh && /bin/oracle --yaml /app/defaults/config.local.three.yml"]

  mongodb:
    image: mongo
    network_mode: host
    volumes:
      - /tmp/data/oracle/mongodb:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"
    command: mongod --quiet --logpath /dev/null
